from typing import Protocol
from uuid import UUID

from stripe_saas_core.domain.stripe_customer import StripeCustomer


class StripeCustomerRepository(Protocol):
    async def get_by_id(self, customer_id: UUID) -> StripeCustomer | None: ...
    async def get_by_stripe_id(self, stripe_id: str) -> StripeCustomer | None: ...
    async def get_by_user_id(self, user_id: UUID) -> StripeCustomer | None: ...
    async def get_by_org_id(self, org_id: UUID) -> StripeCustomer | None: ...
    async def save(self, customer: StripeCustomer) -> StripeCustomer: ...
    async def delete(self, customer_id: UUID) -> None: ...
