# Generated by Django 6.0.3 on 2026-03-12 14:32
# Consolidated from monorepo migrations 0001, 0003, 0004.
# The org FK on StripeCustomer and the exactly-one-owner constraint are deferred
# to a later migration that ships with the orgs app (PR 5).

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "context",
                    models.CharField(
                        choices=[("personal", "Personal"), ("team", "Team")], max_length=20
                    ),
                ),
                (
                    "interval",
                    models.CharField(
                        choices=[("month", "Monthly"), ("year", "Yearly")], max_length=10
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "plans",
            },
        ),
        migrations.CreateModel(
            name="StripeCustomer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("stripe_id", models.CharField(max_length=255, unique=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stripe_customer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("livemode", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "stripe_customers",
            },
        ),
        migrations.CreateModel(
            name="StripeEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("stripe_id", models.CharField(max_length=255, unique=True)),
                ("type", models.CharField(max_length=255)),
                ("livemode", models.BooleanField()),
                ("payload", models.JSONField()),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("error", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "stripe_events",
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("stripe_id", models.CharField(max_length=255, unique=True)),
                (
                    "stripe_customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="billing.stripecustomer",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("trialing", "Trialing"),
                            ("past_due", "Past Due"),
                            ("canceled", "Canceled"),
                            ("incomplete", "Incomplete"),
                            ("incomplete_expired", "Incomplete Expired"),
                            ("paused", "Paused"),
                            ("unpaid", "Unpaid"),
                        ],
                        default="incomplete",
                        max_length=30,
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriptions",
                        to="billing.plan",
                    ),
                ),
                ("quantity", models.IntegerField(default=1)),
                ("promotion_code_id", models.CharField(blank=True, max_length=255, null=True)),
                ("discount_percent", models.IntegerField(blank=True, null=True)),
                ("discount_end_at", models.DateTimeField(blank=True, null=True)),
                ("trial_ends_at", models.DateTimeField(blank=True, null=True)),
                ("current_period_start", models.DateTimeField()),
                ("current_period_end", models.DateTimeField()),
                ("canceled_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "subscriptions",
                "get_latest_by": "created_at",
            },
        ),
        migrations.CreateModel(
            name="PlanPrice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("stripe_price_id", models.CharField(max_length=255, unique=True)),
                ("currency", models.CharField(max_length=3)),
                ("amount", models.IntegerField(help_text="Amount in minor units (cents)")),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="billing.plan",
                    ),
                ),
            ],
            options={
                "db_table": "plan_prices",
            },
        ),
        # Indexes
        migrations.AddIndex(
            model_name="stripeevent",
            index=models.Index(fields=["type"], name="idx_stripe_events_type"),
        ),
        migrations.AddIndex(
            model_name="stripeevent",
            index=models.Index(fields=["-created_at"], name="idx_stripe_events_created_at"),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["stripe_customer", "status"], name="idx_sub_customer_status"
            ),
        ),
        # Constraints
        migrations.AddConstraint(
            model_name="planprice",
            constraint=models.UniqueConstraint(
                fields=("plan", "currency"), name="plan_prices_plan_currency_uniq"
            ),
        ),
        # NOTE: The stripe_customers_exactly_one_owner check constraint and the
        # org OneToOneField are added by the orgs app migration (PR 5).
    ]
