# Generated by Django 6.0.4 on 2026-04-09 09:21

import uuid

import django.core.serializers.json
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("type", models.CharField(choices=[("one_time", "One-time")], max_length=30)),
                ("credits", models.IntegerField(help_text="Number of credits granted on purchase")),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "products",
            },
        ),
        migrations.CreateModel(
            name="StripeCustomer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("stripe_id", models.CharField(max_length=255, unique=True)),
                ("livemode", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "stripe_customers",
            },
        ),
        migrations.CreateModel(
            name="StripeEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("stripe_id", models.CharField(max_length=255, unique=True)),
                ("type", models.CharField(max_length=255)),
                ("livemode", models.BooleanField()),
                (
                    "payload",
                    models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder),
                ),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("error", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "stripe_events",
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("stripe_id", models.CharField(blank=True, max_length=255, null=True, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("trialing", "Trialing"),
                            ("past_due", "Past Due"),
                            ("canceled", "Canceled"),
                            ("incomplete", "Incomplete"),
                            ("incomplete_expired", "Incomplete Expired"),
                            ("paused", "Paused"),
                            ("unpaid", "Unpaid"),
                        ],
                        default="incomplete",
                        max_length=30,
                    ),
                ),
                ("quantity", models.IntegerField(default=1)),
                ("promotion_code_id", models.CharField(blank=True, max_length=255, null=True)),
                ("discount_percent", models.FloatField(blank=True, null=True)),
                ("discount_end_at", models.DateTimeField(blank=True, null=True)),
                ("trial_ends_at", models.DateTimeField(blank=True, null=True)),
                ("current_period_start", models.DateTimeField()),
                ("current_period_end", models.DateTimeField()),
                ("canceled_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "subscriptions",
                "get_latest_by": "created_at",
            },
        ),
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "context",
                    models.CharField(
                        choices=[("personal", "Personal"), ("team", "Team")], max_length=20
                    ),
                ),
                (
                    "tier",
                    models.CharField(
                        choices=[("free", "Free"), ("basic", "Basic"), ("pro", "Pro")],
                        default="basic",
                        max_length=10,
                    ),
                ),
                (
                    "interval",
                    models.CharField(
                        choices=[("month", "Monthly"), ("year", "Yearly")], max_length=10
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "plans",
                "ordering": ("context", "tier", "interval"),
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True)),
                        fields=("context", "tier", "interval"),
                        name="uniq_active_plan_per_context_tier_interval",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PlanPrice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("stripe_price_id", models.CharField(max_length=255, unique=True)),
                ("amount", models.IntegerField(help_text="Amount in USD cents")),
                (
                    "plan",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price",
                        to="billing.plan",
                    ),
                ),
            ],
            options={
                "db_table": "plan_prices",
            },
        ),
        migrations.CreateModel(
            name="ProductPrice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("stripe_price_id", models.CharField(max_length=255, unique=True)),
                ("amount", models.IntegerField(help_text="Amount in USD cents")),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price",
                        to="billing.product",
                    ),
                ),
            ],
            options={
                "db_table": "product_prices",
            },
        ),
    ]
