# Generated by Django 6.0.4 on 2026-04-09 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("billing", "0001_initial"),
        ("orgs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stripecustomer",
            name="org",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stripe_customer",
                to="orgs.org",
            ),
        ),
    ]
