# Generated by Django 6.0.3 on 2026-03-25 12:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="stripecustomer",
            constraint=models.CheckConstraint(
                condition=models.Q(("user_id__isnull", False)), name="stripecustomer_has_owner"
            ),
        ),
    ]
