# Generated by Django 6.0.4 on 2026-04-09 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("billing", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="stripecustomer",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stripe_customer",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="stripeevent",
            index=models.Index(fields=["type"], name="idx_stripe_events_type"),
        ),
        migrations.AddIndex(
            model_name="stripeevent",
            index=models.Index(fields=["-created_at"], name="idx_stripe_events_created_at"),
        ),
        migrations.AddField(
            model_name="subscription",
            name="plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subscriptions",
                to="billing.plan",
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="stripe_customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscriptions",
                to="billing.stripecustomer",
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscriptions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="stripecustomer",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("org_id__isnull", True), ("user_id__isnull", False)),
                    models.Q(("org_id__isnull", False), ("user_id__isnull", True)),
                    _connector="OR",
                ),
                name="stripecustomer_has_owner",
            ),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["stripe_customer", "status"], name="idx_sub_customer_status"
            ),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(fields=["user", "status"], name="idx_sub_user_status"),
        ),
    ]
