# Generated by Django 6.0.4 on 2026-04-09 15:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0003_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="subscription",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("user__isnull", False), ("stripe_customer__isnull", False), _connector="OR"
                ),
                name="subscription_has_owner",
            ),
        ),
    ]
