# Generated by Django 6.0.3 on 2026-04-06 09:56

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0003_add_org_fk_to_stripe_customer"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("type", models.CharField(choices=[("one_time", "One-time")], max_length=30)),
                ("credits", models.IntegerField(help_text="Number of credits granted on purchase")),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "products",
            },
        ),
        migrations.CreateModel(
            name="ProductPrice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("stripe_price_id", models.CharField(max_length=255, unique=True)),
                ("currency", models.CharField(max_length=3)),
                ("amount", models.IntegerField(help_text="Amount in minor units (cents)")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="billing.product",
                    ),
                ),
            ],
            options={
                "db_table": "product_prices",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("product", "currency"), name="product_prices_product_currency_uniq"
                    )
                ],
            },
        ),
    ]
