# Generated by Django 6.0.4 on 2026-04-09 18:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0004_subscription_subscription_has_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="discount_end_at",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="discount_percent",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="promotion_code_id",
        ),
    ]
