# Generated by Django 6.0.3 on 2026-04-06 09:56

import uuid

from django.db import migrations

BOOST_1_ID = uuid.UUID("a1b2c3d4-0001-4000-8000-000000000001")
BOOST_2_ID = uuid.UUID("a1b2c3d4-0002-4000-8000-000000000002")

BOOST_PRODUCTS = [
    {"id": BOOST_1_ID, "name": "Boost 1", "type": "one_time", "credits": 40},
    {"id": BOOST_2_ID, "name": "Boost 2", "type": "one_time", "credits": 100},
]

BOOST_PRICES = [
    {
        "product_id": BOOST_1_ID,
        "stripe_price_id": "price_boost_1_usd",
        "currency": "usd",
        "amount": 900,
    },
    {
        "product_id": BOOST_2_ID,
        "stripe_price_id": "price_boost_2_usd",
        "currency": "usd",
        "amount": 1900,
    },
]


def seed_boosts(apps, schema_editor):
    Product = apps.get_model("billing", "Product")
    ProductPrice = apps.get_model("billing", "ProductPrice")
    for p in BOOST_PRODUCTS:
        Product.objects.get_or_create(id=p["id"], defaults=p)
    for pp in BOOST_PRICES:
        ProductPrice.objects.get_or_create(
            product_id=pp["product_id"],
            currency=pp["currency"],
            defaults=pp,
        )


def remove_boosts(apps, schema_editor):
    Product = apps.get_model("billing", "Product")
    Product.objects.filter(id__in=[BOOST_1_ID, BOOST_2_ID]).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0004_add_product_and_product_price"),
    ]

    operations = [
        migrations.RunPython(seed_boosts, remove_boosts),
    ]
