# Generated by Django 6.0.3 on 2026-04-06 10:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0005_seed_boost_products"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
    ]
