# Generated by Django 6.0.4 on 2026-04-13 10:55

from __future__ import annotations

from django.db import migrations

# (name, credit_count, amount_usd_cents, placeholder_stripe_price_id)
BOOST_PRODUCTS = [
    ("50 Credits", 50, 499, "price_placeholder_boost_50"),
    ("200 Credits", 200, 1499, "price_placeholder_boost_200"),
    ("500 Credits", 500, 2999, "price_placeholder_boost_500"),
]


def seed_boost_products(apps, schema_editor):  # type: ignore[no-untyped-def]
    Product = apps.get_model("billing", "Product")
    ProductPrice = apps.get_model("billing", "ProductPrice")

    for name, credit_count, amount, stripe_price_id in BOOST_PRODUCTS:
        product, _ = Product.objects.get_or_create(
            name=name,
            defaults={"type": "one_time", "credits": credit_count, "is_active": True},
        )
        ProductPrice.objects.get_or_create(
            product=product,
            defaults={"stripe_price_id": stripe_price_id, "amount": amount},
        )


def remove_boost_products(apps, schema_editor):  # type: ignore[no-untyped-def]
    Product = apps.get_model("billing", "Product")
    names = [name for name, *_ in BOOST_PRODUCTS]
    Product.objects.filter(name__in=names).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0006_exchangerate"),
    ]

    operations = [
        migrations.RunPython(seed_boost_products, remove_boost_products),
    ]
