# Generated by Django 6.0.4 on 2026-04-13 10:55
#
# Historically this migration seeded three Boost products as a data migration.
# The deploy entrypoint now runs `manage.py seed_catalog` after `migrate` on
# every boot, and that command is idempotent and authoritative — keeping the
# seed here created a second source of truth that would silently no-op
# whenever `seed_catalog` diverged (different name, price, credit count).
#
# The migration is retained (rather than squashed) so its primary-key position
# in the migration graph stays stable for existing deployments. Forward is a
# no-op; reverse is left as a no-op too because production DBs have already
# been seeded via this migration and the rows must survive a rollback.

from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0006_exchangerate"),
    ]

    operations = [
        migrations.RunPython(migrations.RunPython.noop, migrations.RunPython.noop),
    ]
