# Generated by Django 6.0.4 on 2026-04-15 13:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_exchangerate_currency_pk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exchangerate',
            options={'ordering': ('currency',)},
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(condition=models.Q(('status__in', ('active', 'trialing', 'past_due'))), fields=['stripe_customer', 'user'], name='idx_sub_active_owner'),
        ),
    ]
