# Generated by Django 6.0.4 on 2026-04-16 09:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0011_performance_audit_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="subscription",
            constraint=models.UniqueConstraint(
                condition=models.Q(("stripe_id__isnull", True)),
                fields=("user",),
                name="uniq_free_subscription_per_user",
            ),
        ),
    ]
