# Generated by Django 6.0.4 on 2026-04-24 09:54

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0012_paid_free_invariant"),
        ("orgs", "0008_performance_audit_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CreditBalance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("balance", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "org",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit_balance",
                        to="orgs.org",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit_balance",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "credit_balances",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("org_id__isnull", True), ("user_id__isnull", False)),
                            models.Q(("org_id__isnull", False), ("user_id__isnull", True)),
                            _connector="OR",
                        ),
                        name="creditbalance_has_owner",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("balance__gte", 0)), name="creditbalance_non_negative"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CreditTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("amount", models.IntegerField(help_text="Positive = grant, negative = consume.")),
                ("reason", models.CharField(max_length=64)),
                (
                    "stripe_session_id",
                    models.CharField(blank=True, max_length=255, null=True, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "org",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit_transactions",
                        to="orgs.org",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "credit_transactions",
                "indexes": [
                    models.Index(fields=["user", "-created_at"], name="idx_credit_tx_user_created"),
                    models.Index(fields=["org", "-created_at"], name="idx_credit_tx_org_created"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("org_id__isnull", True), ("user_id__isnull", False)),
                            models.Q(("org_id__isnull", False), ("user_id__isnull", True)),
                            _connector="OR",
                        ),
                        name="credittransaction_has_owner",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("amount", 0), _negated=True),
                        name="credittransaction_nonzero_amount",
                    ),
                ],
            },
        ),
    ]
