from typing import Protocol
from uuid import UUID

from saasmint_core.domain.org import Org, OrgMember


class OrgRepository(Protocol):
    async def get_by_id(self, org_id: UUID) -> Org | None: ...
    async def get_by_slug(self, slug: str) -> Org | None: ...
    async def save(self, org: Org) -> Org: ...
    async def delete(self, org_id: UUID) -> None: ...


class OrgMemberRepository(Protocol):
    async def get(self, org_id: UUID, user_id: UUID) -> OrgMember | None: ...
    async def list_by_org(self, org_id: UUID) -> list[OrgMember]: ...
    async def list_by_user(self, user_id: UUID) -> list[OrgMember]: ...
    async def save(self, member: OrgMember) -> OrgMember: ...
    async def delete(self, org_id: UUID, user_id: UUID) -> None: ...
    async def count_active(self, org_id: UUID) -> int: ...
