from typing import Protocol
from uuid import UUID

from saasmint_core.domain.subscription import Plan, PlanPrice


class PlanRepository(Protocol):
    async def get_by_id(self, plan_id: UUID) -> Plan | None: ...
    async def list_active(self) -> list[Plan]: ...
    async def get_price(self, plan_id: UUID) -> PlanPrice | None: ...
    async def get_price_by_stripe_id(self, stripe_price_id: str) -> PlanPrice | None: ...
