from typing import Protocol
from uuid import UUID

from saasmint_core.domain.product import Product, ProductPrice


class ProductRepository(Protocol):
    async def get_by_id(self, product_id: UUID) -> Product | None: ...
    async def list_active(self) -> list[Product]: ...
    async def get_price(self, product_id: UUID) -> ProductPrice | None: ...
    async def get_price_by_stripe_id(self, stripe_price_id: str) -> ProductPrice | None: ...
