from typing import Protocol
from uuid import UUID

from saasmint_core.domain.subscription import Subscription


class SubscriptionRepository(Protocol):
    async def get_by_id(self, subscription_id: UUID) -> Subscription | None: ...
    async def get_by_stripe_id(self, stripe_id: str) -> Subscription | None: ...
    async def get_active_for_customer(self, stripe_customer_id: UUID) -> Subscription | None: ...
    async def save(self, subscription: Subscription) -> Subscription: ...
    async def delete(self, subscription_id: UUID) -> None: ...
