from typing import Protocol
from uuid import UUID

from saasmint_core.domain.user import User


class UserRepository(Protocol):
    async def get_by_id(self, user_id: UUID) -> User | None: ...
    async def get_by_email(self, email: str) -> User | None: ...
    async def get_by_supabase_uid(self, supabase_uid: str) -> User | None: ...
    async def save(self, user: User) -> User: ...
    async def delete(self, user_id: UUID) -> None: ...
    async def list_by_org(
        self, org_id: UUID, *, limit: int = 100, offset: int = 0
    ) -> list[User]: ...
