# Generated by Django 6.0.4 on 2026-04-09 10:27

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_emailverificationtoken_passwordresettoken_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="registration_method",
            field=models.CharField(
                choices=[
                    ("email", "Email"),
                    ("google", "Google"),
                    ("github", "GitHub"),
                    ("microsoft", "Microsoft"),
                ],
                default="email",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="SocialAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("provider", models.CharField(max_length=20)),
                ("provider_user_id", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "social_accounts",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("provider", "provider_user_id"), name="uq_social_provider_uid"
                    ),
                    models.UniqueConstraint(
                        fields=("user", "provider"), name="uq_social_user_provider"
                    ),
                ],
            },
        ),
    ]
