# Generated by Django 6.0.4 on 2026-04-09 15:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_user_registration_method_socialaccount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="refreshtoken",
            name="token_hash",
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
