# Generated by Django 6.0.4 on 2026-04-13 13:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_remove_redundant_token_hash_db_index"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="deleted_at",
        ),
        migrations.RemoveField(
            model_name="user",
            name="scheduled_deletion_at",
        ),
    ]
