# Generated by Django 6.0.3 on 2026-04-02 10:56

import django.core.validators
from django.db import migrations, models


def backfill_full_name(apps, schema_editor):
    User = apps.get_model("users", "User")
    User.objects.filter(full_name__isnull=True).update(full_name="")


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_add_phone_timezone_job_title_bio'),
    ]

    operations = [
        migrations.RunPython(backfill_full_name, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
