# Generated by Django 6.0.3 on 2026-04-03 10:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_add_pronouns"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="scheduled_deletion_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
