# Generated by Django 6.0.3 on 2026-03-19 16:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orgs", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="orgmember",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="org",
            name="deleted_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name="org",
            index=models.Index(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=["slug"],
                name="idx_orgs_slug_active",
            ),
        ),
        migrations.AddConstraint(
            model_name="orgmember",
            constraint=models.UniqueConstraint(
                fields=("org", "user"), name="org_members_org_user_uniq"
            ),
        ),
    ]
