# Generated by Django 6.0.4 on 2026-04-13 12:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orgs", "0004_alter_org_created_by_set_null"),
    ]

    operations = [
        migrations.AddField(
            model_name="org",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
