# Generated by Django 6.0.4 on 2026-04-15 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0006_invitation_status_declined'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='invitation',
            name='idx_invitations_token',
        ),
    ]
