# Generated by Django 6.0.4 on 2026-04-16 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orgs", "0007_django_audit_medium_low"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="invitation",
            index=models.Index(
                condition=models.Q(("status", "pending")),
                fields=["org", "-created_at"],
                name="idx_invitation_pending_org",
            ),
        ),
        migrations.AddIndex(
            model_name="orgmember",
            index=models.Index(
                condition=models.Q(("is_billing", True)),
                fields=["user"],
                name="idx_orgmember_billing_user",
            ),
        ),
    ]
